src/Entity/Filtre.php
<?php

namespace AcMarche\Pivot\Entity;

use AcMarche\Pivot\Entities\Label;
use AcMarche\Pivot\Entities\LabelTrait;
use AcMarche\Pivot\Repository\FiltreRepository;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;

#[ORM\Entity(repositoryClass: FiltreRepository::class)]
#[ORM\Table(name: 'pivot_filtre')]
class Filtre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    public int $id;
    #[ORM\Column(type: 'string', length: 180)]
    public string $nom;
    #[ORM\Column(type: 'string', nullable: true, length: 50)]
    public ?string $code = null;
    #[ORM\Column(type: 'boolean')]
    public bool $root = false;
    #[ORM\Column(type: 'string', length: 250, nullable: true)]
    public ?string $urn;
    #[ORM\Column(type: 'integer', unique: false, nullable: false)]
    public int $reference;
    #[ORM\ManyToOne(targetEntity: Filtre::class)]
    #[ORM\JoinColumn(name: 'parent_id', referencedColumnName: 'id', nullable: true, onDelete: 'CASCADE')]
    public ?Filtre $parent = null;
    #[ORM\Column(type: 'string', length: 180, nullable: true)]
    public ?string $name_fr;
    #[ORM\Column(type: 'string', length: 180, nullable: true)]
    public ?string $name_nl;
    #[ORM\Column(type: 'string', length: 180, nullable: true)]
    public ?string $name_en;
    #[ORM\Column(type: 'string', length: 180, nullable: true)]
    public ?string $name_de;

    /**
     * @var Filtre[] $children
     */
    public array $children = [];

    public function __construct(
        string $nom,
        int $reference,
        ?string $urn,
        ?Filtre $parent,
        ?string $name_nl = null,
        ?string $name_en = null,
        ?string $name_de = null
    ) {
        $this->reference = $reference;
        $this->nom = $nom;
        $this->urn = $urn;
        $this->parent = $parent;
        $this->name_nl = $name_nl;
        $this->name_en = $name_en;
        $this->name_de = $name_de;
    }

    public function __toString(): string
    {
        return $this->nom;
    }

    public function labelByLanguage(string $language = Label::FR): string
    {
        $property = 'name_'.$language;
        if (isset($this->$property) && $this->$property != null) {
            return $this->$property;
        } else {
            return $this->nom;
        }
    }

    public function getIdentifiant(): string|int
    {
        if ($this->root) {
            return $this->reference;
        } else {
            return $this->urn;
        }
    }
}

templates/filter/_flags.html.twig
<div class="d-flex flex-nowrap gap-2">
    {% if filter.name_fr %}
        <img src="{{ asset('bundles/acmarchepivot/images/fr.png') }}" alt="drapeau fr"
             style="width: 30px; height: 30px;"
             title="Fr: {{ filter.name_fr }}">
    {% endif %}

    {% if filter.name_nl %}
        <img src="{{ asset('bundles/acmarchepivot/images/nl.png') }}" alt="drapeau nl"
             style="width: 30px; height: 30px;"
             title="Nl: {{ filter.name_nl }}">
    {% endif %}

    {% if filter.name_fr %}
        <img src="{{ asset('bundles/acmarchepivot/images/en.png') }}" alt="drapeau en"
             style="width: 30px; height: 30px;"
             title="En: {{ filter.name_en }}">
    {% endif %}
</div>

templates/filter/edit.html.twig
{% extends '@AcMarchePivot/layout.html.twig' %}

{% block body %}

    <div class="card">
        <h3 class="card-header">{{ filter.nom }}</h3>

        <div class="card-body">
            {{ form_start(form) }}
            {{ form_errors(form) }}
            {{ form_row(form.name_fr) }}
            {{ form_row(form.name_en) }}
            {{ form_row(form.name_nl) }}

            <button type="submit" name="save" class="btn btn-primary"><i class="fas fa-save"></i> Sauvegarder</button>

            {{ form_end(form) }}
        </div>

        <div class="card-footer">

        </div>

    </div>
{% endblock %}

templates/filter/index.html.twig
{% extends '@AcMarchePivot/layout.html.twig' %}

{% block body %}

    <div class="card">
        <h3 class="card-header">Filtres hades pour pivotmarche.be</h3>
        <div class="card-body">

            {% include '@AcMarchePivot/filter/_search.html.twig' %}

            <table class="table table-bordered table-striped">
                <tr>
                    <th>Lvl1</th>
                    <th>Lvl2</th>
                    <th>Traductions</th>
                    <th>Mot clef</th>
                </tr>
                {% for lvl1 in filters %}
                    {% include '@AcMarchePivot/filter/_line.html.twig' with {'filter':lvl1, 'level':1} %}
                    {% for lvl2 in lvl1.children %}
                        {% include '@AcMarchePivot/filter/_line.html.twig' with {'filter':lvl2, 'level':2} %}
                    {% endfor %}
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/filter/search.html.twig
{% extends '@AcMarchePivot/layout.html.twig' %}

{% block body %}

    <div class="card">
        <h3 class="card-header">Recherche</h3>
        <div class="card-body">

            {% include '@AcMarchePivot/filter/_search.html.twig' %}

            <table class="table table-bordered table-striped">
                <tr>
                    <th>Nom</th>
                    <th>Mot clef</th>
                    <th>Traductions</th>
                    <th></th>
                </tr>
                {% for filter in filters %}
                    <tr>
                        <td>{{ filter }}</td>
                        <td>{{ filter.identifiant }}</td>
                        <td>
                            {% include '@AcMarchePivot/filter/_flags.html.twig' %}
                        </td>
                        <td>
                            {% if  filter.identifiant %}
                                <a href="{{ path('pivot_filtre_edit', {'id': filter.id}) }}" title="Traduire">
                                    <i class="fas fa-pencil-alt"></i>
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

templates/filter/show.html.twig
{% extends '@AcMarchePivot/layout.html.twig' %}

{% block body %}

    <div class="card">
        <h3 class="card-header">{{ filter.nom }}</h3>
        <div class="card-body">
            {% include '@AcMarchePivot/filter/_actions.html.twig' %}
            <table class="table table-bordered">
                <tr>
                    <th>Français</th>
                    <td>{{ filter.name_fr }}</td>
                </tr>
                <tr>
                    <th>Anglais</th>
                    <td>{{ filter.name_en }}</td>
                </tr>
                <tr>
                    <th>Néerlandais</th>
                    <td>{{ filter.name_nl }}</td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}